#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generates the tables the layer needs to know Vulkan's feature structures by.

A feature structure is a block of on/off switches an application chains to a
query or to device creation. The layer has to answer for every one of them,
including ones it has never heard of in any other sense: a switch it reports
as on is a promise that the application may use what it stands for. So the
rule is the reverse of forwarding: every switch is off unless OFFERED below
names it, and then it is on only if the driver has it too.

Usage: gen_layer_tables.py OUTPUT.h [--registry vk.xml]
"""
import sys

from zss_registry import Registry

# Switches the layer lets through. Each needs nothing of the layer beyond
# passing shaders and values along unchanged; anything that brings commands,
# objects or structures of its own stays out until the layer tracks it.
OFFERED = {
    "VkPhysicalDeviceShaderDrawParametersFeatures": ["shaderDrawParameters"],
    "VkPhysicalDeviceVariablePointersFeatures": ["variablePointersStorageBuffer", "variablePointers"],
    "VkPhysicalDevice16BitStorageFeatures": ["storageBuffer16BitAccess", "uniformAndStorageBuffer16BitAccess",
                                             "storagePushConstant16", "storageInputOutput16"],
    "VkPhysicalDeviceVulkan11Features": ["storageBuffer16BitAccess", "uniformAndStorageBuffer16BitAccess",
                                         "storagePushConstant16", "storageInputOutput16",
                                         "variablePointersStorageBuffer", "variablePointers", "shaderDrawParameters",
                                         "samplerYcbcrConversion"],
    # The conversion object is tracked and rebuilt (device.c). Images of more
    # than one plane are not carried across yet, so the format queries report
    # those formats as unsupported; see zss_format_planar().
    "VkPhysicalDeviceSamplerYcbcrConversionFeatures": ["samplerYcbcrConversion"],
}

# Device extensions the layer offers besides the swapchain. Each has to be on
# the driver as well, and on every driver the application is later moved to.
OFFERED_EXTENSIONS = [
    "VK_EXT_provoking_vertex",
    "VK_KHR_image_format_list",
    # Recorded and replayed in cmd.c; what the GPU captures is read back with every other GPU-written buffer.
    "VK_EXT_transform_feedback",
]
OFFERED["VkPhysicalDeviceTransformFeedbackFeaturesEXT"] = ["transformFeedback", "geometryStreams"]
OFFERED["VkPhysicalDeviceProvokingVertexFeaturesEXT"] = ["provokingVertexLast"]

# Structures an application may chain to a creation call and that the layer
# keeps with the object and passes on. Only "flat" ones qualify: plain values
# and no handles, so a copy is the whole of it and nothing in it needs
# translating when the object is rebuilt on another GPU. One list of plain
# values with its counter beside it is allowed and copied along.
OFFERED_CHAIN = [
    "VkImageFormatListCreateInfo",
    "VkImageViewUsageCreateInfo",
    "VkPipelineTessellationDomainOriginStateCreateInfo",
    "VkPipelineRasterizationProvokingVertexStateCreateInfoEXT",
    "VkPipelineRasterizationStateStreamCreateInfoEXT",
]

args = sys.argv[1:]
reg = Registry(args[args.index("--registry") + 1] if "--registry" in args else None)
feats = reg.feature_structs()
for name, members in OFFERED.items():
    missing = [m for m in members if m not in feats.get(name, [])]
    if name not in feats or missing:
        sys.exit(f"gen_layer_tables.py: OFFERED names something the registry does not have: {name} {missing}")

o = ["/* SPDX-License-Identifier: GPL-2.0-only */",
     "/* Generated by tools/gen_layer_tables.py from the Vulkan registry. Do not edit. */",
     "#ifndef ZSS_FEATS_GEN_H", "#define ZSS_FEATS_GEN_H", "",
     "/* One feature structure: its type, how many switches follow the header, and which of them the layer offers. */",
     "struct zss_feat_struct { VkStructureType stype; const char *name; uint32_t n; uint64_t offered[2]; const char *const *members; };", ""]
rows = []
for name in sorted(feats):
    members = feats[name]
    if len(members) > 128:
        sys.exit(f"{name} has more than 128 switches")
    mask = [0, 0]
    for i, m in enumerate(members):
        if m in OFFERED.get(name, []):
            mask[i // 64] |= 1 << (i % 64)
    o.append(f"static const char *const zss_fm_{name}[] = {{ " + ", ".join(f'"{m}"' for m in members) + " };")
    rows.append(f'    {{ (VkStructureType){reg.enum_values[reg.structs[name]["stype"]]}, "{name}", {len(members)}, '
                f'{{ 0x{mask[0]:x}ull, 0x{mask[1]:x}ull }}, zss_fm_{name} }},')
o += ["", "static const struct zss_feat_struct zss_feat_structs[] = {"] + rows + ["};", ""]

HANDLES = {t for t in ("VkBuffer", "VkImage", "VkImageView", "VkSampler", "VkDeviceMemory", "VkRenderPass", "VkFramebuffer",
                       "VkPipeline", "VkPipelineLayout", "VkDescriptorSet", "VkDescriptorSetLayout", "VkSemaphore", "VkFence",
                       "VkSwapchainKHR", "VkSurfaceKHR", "VkDevice", "VkQueue", "VkCommandBuffer", "VkShaderModule",
                       "VkSamplerYcbcrConversion", "VkBufferView", "VkPipelineCache", "VkQueryPool", "VkEvent")}
o += ["/* Structures kept from a creation call's chain: type and size, and where its one list is if it has one. */",
      "static const struct zss_chain_struct { VkStructureType stype; size_t size; const char *name;",
      "                                       size_t list, count, each; } zss_chain_structs[] = {"]
for name in OFFERED_CHAIN:
    s = reg.structs.get(name)
    if not s or not s["stype"]:
        sys.exit(f"gen_layer_tables.py: OFFERED_CHAIN names an unknown structure: {name}")
    lst = "0, 0, 0"
    for mtype, mname, text in s["members"]:
        if mname == "pNext":
            continue
        counter = s["lens"].get(mname)
        if mtype in HANDLES or mtype in reg.structs or text.count("*") > 1 or ("*" in text and not counter):
            sys.exit(f"gen_layer_tables.py: {name}.{mname} is a handle, a structure or a bare pointer; not flat")
        if "*" in text:
            if lst != "0, 0, 0" or counter not in [m[1] for m in s["members"]]:
                sys.exit(f"gen_layer_tables.py: {name}.{mname}: only one list, counted by a member, is copied")
            lst = f"offsetof({name}, {mname}), offsetof({name}, {counter}), sizeof({mtype})"
    o.append(f'    {{ (VkStructureType){reg.enum_values[s["stype"]]}, sizeof({name}), "{name}", {lst} }},')
o += ["};", "", "static const char *const zss_offered_exts[] = {"]
for e in OFFERED_EXTENSIONS:
    if e not in reg.extensions:
        sys.exit(f"gen_layer_tables.py: OFFERED_EXTENSIONS names an unknown extension: {e}")
    o.append(f'    "{e}",')
o += ["};", ""]

# How each limit of a device combines with another device's into the weaker
# of the two, taken from the registry's own note on which direction is better.
import xml.etree.ElementTree as ET
KIND = {"max": "ZL_LEAST", "bits": "ZL_LEAST", "max,pot": "ZL_LEAST", "min": "ZL_MOST", "min,mul": "ZL_MOST",
        "min,pot": "ZL_MOST", "bitmask": "ZL_BOTH", "range": "ZL_RANGE"}
CTYPE = {"uint32_t": "ZT_U32", "int32_t": "ZT_I32", "float": "ZT_F32", "size_t": "ZT_SIZE", "VkDeviceSize": "ZT_U64",
         "VkBool32": "ZT_U32", "VkSampleCountFlags": "ZT_U32"}
lim = ["/* VkPhysicalDeviceLimits, member by member: where it is, what it holds, and which value is the weaker. */",
       "enum zss_limit_kind { ZL_LEAST, ZL_MOST, ZL_BOTH, ZL_RANGE };",
       "enum zss_limit_type { ZT_U32, ZT_I32, ZT_F32, ZT_SIZE, ZT_U64 };",
       "static const struct zss_limit { size_t off; enum zss_limit_kind kind; enum zss_limit_type type; uint32_t n; "
       "const char *name; } zss_limits[] = {"]
for t in ET.parse(reg.path).getroot().find("types"):
    if t.get("name") != "VkPhysicalDeviceLimits":
        continue
    for m in t.findall("member"):
        name, mtype, lt = m.find("name").text, m.find("type").text, m.get("limittype")
        if lt not in KIND or mtype not in CTYPE:
            sys.exit(f"gen_layer_tables.py: VkPhysicalDeviceLimits.{name}: no rule for {lt} {mtype}")
        text = "".join(m.itertext())
        n = int(text[text.index("[") + 1:text.index("]")]) if "[" in text else 1
        lim.append(f'    {{ offsetof(VkPhysicalDeviceLimits, {name}), {KIND[lt]}, {CTYPE[mtype]}, {n}, "{name}" }},')
lim += ["};", ""]

# One translation unit wants the feature tables, another the limits; neither wants unused tables.
out = o[:5] + ["#ifdef ZSS_GEN_LIMITS"] + lim + ["#else"] + o[5:] + ["#endif", "", "#endif"]
open(args[0], "w").write("\n".join(out) + "\n")
