#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generates the survey layer: an ordinary Vulkan layer that only watches.

It counts every command an application calls and notes what the application
asked for when it created its instance and device, and writes that to a file.
It changes nothing: every call is passed on untouched. See tools/zss-survey.

Usage: gen_survey.py OUTPUT.c [--registry vk.xml]
"""
import sys

from zss_registry import Registry

args = sys.argv[1:]
reg = Registry(args[args.index("--registry") + 1] if "--registry" in args else None)
out_path = args[0]

SPECIAL = {"vkCreateInstance", "vkCreateDevice", "vkDestroyInstance", "vkDestroyDevice", "vkGetInstanceProcAddr",
           "vkGetDeviceProcAddr", "vkEnumerateDeviceExtensionProperties", "vkGetPhysicalDeviceFeatures2",
           "vkGetPhysicalDeviceFeatures2KHR", "vkGetPhysicalDeviceProperties", "vkGetPhysicalDeviceProperties2",
           "vkGetPhysicalDeviceProperties2KHR"}
names = [n for n in reg.buildable() if reg.commands[n].level != "global" or n == "vkCreateInstance"]
index = {n: i for i, n in enumerate(names)}

o = []
w = o.append
w("// SPDX-License-Identifier: GPL-2.0-only")
w("/* Generated by tools/gen_survey.py from the Vulkan registry. Do not edit. */")
w("#define VK_USE_PLATFORM_XCB_KHR\n#define VK_USE_PLATFORM_XLIB_KHR\n#define VK_USE_PLATFORM_WAYLAND_KHR")
w("#include <vulkan/vulkan.h>\n#include <vulkan/vk_layer.h>")
w("#include <pthread.h>\n#include <stdarg.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <unistd.h>\n")
w(f"#define ZSV_NCMD {len(names)}")
w("static const char *const zsv_names[ZSV_NCMD] = {")
for n in names:
    w(f'    "{n}",')
w("};")
w("/* 'i' instance level, 'd' device level. */")
w('static const char zsv_level[ZSV_NCMD + 1] = "' + "".join(reg.commands[n].level[0] if n != "vkCreateInstance" else "i"
                                                         for n in names) + '";')
w("static unsigned long zsv_count[ZSV_NCMD];")
w("""
struct zsv_table { void *key; void *handle; PFN_vkVoidFunction fn[ZSV_NCMD]; PFN_vkGetInstanceProcAddr gipa; PFN_vkGetDeviceProcAddr gdpa; };
#define ZSV_MAX 32
static struct zsv_table *zsv_tables[ZSV_MAX];
static pthread_mutex_t zsv_lock = PTHREAD_MUTEX_INITIALIZER;

static struct zsv_table *zsv_find(void *dispatchable)
{
    void *key = *(void **)dispatchable;
    struct zsv_table *t = NULL;

    pthread_mutex_lock(&zsv_lock);
    for (int i = 0; i < ZSV_MAX; i++)
        if (zsv_tables[i] && zsv_tables[i]->key == key)
            t = zsv_tables[i];
    pthread_mutex_unlock(&zsv_lock);
    return t;
}

static void zsv_add(struct zsv_table *t)
{
    pthread_mutex_lock(&zsv_lock);
    for (int i = 0; i < ZSV_MAX; i++) {
        if (!zsv_tables[i]) {
            zsv_tables[i] = t;
            break;
        }
    }
    pthread_mutex_unlock(&zsv_lock);
}

static void zsv_remove(struct zsv_table *t)
{
    pthread_mutex_lock(&zsv_lock);
    for (int i = 0; i < ZSV_MAX; i++)
        if (zsv_tables[i] == t)
            zsv_tables[i] = NULL;
    pthread_mutex_unlock(&zsv_lock);
    free(t);
}
""")

# ---- what the application asked for --------------------------------------------------
stypes = {v: k for k, v in reg.enum_values.items() if k.startswith("VK_STRUCTURE_TYPE_")}
w("static const struct { int value; const char *name; } zsv_stypes[] = {")
for v in sorted(stypes):
    w(f'    {{ {v}, "{stypes[v]}" }},')
w("};")
features = reg.feature_structs()
w("static const struct zsv_feat { int stype; const char *name; int n; const char *const *members; } zsv_feats[] = {")
decls = []
for name in sorted(features):
    ident = "zsv_m_" + name
    decls.append(f"static const char *const {ident}[] = {{ " + ", ".join(f'"{m}"' for m in features[name]) + " };")
    w(f'    {{ {reg.enum_values[reg.structs[name]["stype"]]}, "{name}", {len(features[name])}, {ident} }},')
w("};")
base = [m[1] for m in reg.structs["VkPhysicalDeviceFeatures"]["members"]]
o.insert(o.index("static const struct zsv_feat { int stype; const char *name; int n; const char *const *members; } zsv_feats[] = {"),
         "\n".join(decls) + "\nstatic const char *const zsv_base_features[] = { " + ", ".join(f'"{m}"' for m in base) + " };")

w(r"""
#define ZSV_NOTES 65536
static char zsv_notes[ZSV_NOTES];
static void zsv_note(const char *fmt, ...) __attribute__((format(printf, 1, 2)));
static void zsv_note(const char *fmt, ...)
{
    va_list ap;
    size_t used;

    pthread_mutex_lock(&zsv_lock);
    used = strlen(zsv_notes);
    va_start(ap, fmt);
    vsnprintf(zsv_notes + used, ZSV_NOTES - used, fmt, ap);
    va_end(ap);
    pthread_mutex_unlock(&zsv_lock);
}

static const char *zsv_stype_name(int v)
{
    for (size_t i = 0; i < sizeof(zsv_stypes) / sizeof(zsv_stypes[0]); i++)
        if (zsv_stypes[i].value == v)
            return zsv_stypes[i].name;
    return "?";
}

static void zsv_base(const char *what, const VkPhysicalDeviceFeatures *f)
{
    const VkBool32 *b = (const VkBool32 *)f;

    for (size_t i = 0; f && i < sizeof(zsv_base_features) / sizeof(zsv_base_features[0]); i++)
        if (b[i])
            zsv_note("feature\t%s\tVkPhysicalDeviceFeatures.%s\n", what, zsv_base_features[i]);
}

/* Every structure chained to a create call, and every feature switch that is on. */
static void zsv_chain(const char *what, const void *pnext)
{
    for (const VkBaseInStructure *s = pnext; s; s = s->pNext) {
        if (s->sType == VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO || s->sType == VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO)
            continue;
        zsv_note("struct\t%s\t%s\n", what, zsv_stype_name((int)s->sType));
        if (s->sType == VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2)
            zsv_base(what, &((const VkPhysicalDeviceFeatures2 *)s)->features);
        for (size_t i = 0; i < sizeof(zsv_feats) / sizeof(zsv_feats[0]); i++) {
            const VkBool32 *b = (const VkBool32 *)(s + 1);

            if (zsv_feats[i].stype != (int)s->sType)
                continue;
            for (int k = 0; k < zsv_feats[i].n; k++)
                if (b[k])
                    zsv_note("feature\t%s\t%s.%s\n", what, zsv_feats[i].name, zsv_feats[i].members[k]);
        }
    }
}

static void zsv_write(void)
{
    const char *dir = getenv("ZSS_SURVEY_DIR");
    char path[512], tmp[540], exe[256] = "?";
    ssize_t n = readlink("/proc/self/exe", exe, sizeof(exe) - 1);
    FILE *f;

    if (n > 0)
        exe[n] = '\0';
    snprintf(path, sizeof(path), "%s/survey-%d.tsv", dir ? dir : ".", (int)getpid());
    snprintf(tmp, sizeof(tmp), "%s.tmp", path);
    f = fopen(tmp, "w");
    if (!f)
        return;
    fprintf(f, "exe\t%s\n", exe);
    pthread_mutex_lock(&zsv_lock);
    fputs(zsv_notes, f);
    pthread_mutex_unlock(&zsv_lock);
    for (int i = 0; i < ZSV_NCMD; i++)
        if (zsv_count[i])
            fprintf(f, "command\t%s\t%lu\n", zsv_names[i], zsv_count[i]);
    fclose(f);
    rename(tmp, path);
}

/* Applications are often killed rather than closed, so the report is rewritten as they run. */
static void *zsv_writer(void *arg)
{
    (void)arg;
    for (;;) {
        /* Often enough to catch a process that gives up and exits within a second. */
        usleep(50000);
        zsv_write();
    }
    return NULL;
}

static void zsv_start(void)
{
    static int started;
    pthread_t tid;

    pthread_mutex_lock(&zsv_lock);
    if (!started) {
        started = 1;
        if (pthread_create(&tid, NULL, zsv_writer, NULL) == 0)
            pthread_detach(tid);
        atexit(zsv_write);
    }
    pthread_mutex_unlock(&zsv_lock);
}
""")

# ---- one wrapper per command ---------------------------------------------------------
for n in names:
    if n in SPECIAL:
        continue
    c = reg.commands[n]
    guard = reg.guard(n)
    if guard:
        w(f"#ifdef {guard}")
    decl = ", ".join(p[0] for p in c.params)
    call = ", ".join(p[1] for p in c.params)
    w(f"static VKAPI_ATTR {c.ret} VKAPI_CALL zsv_{n[2:]}({decl})")
    w("{")
    w(f"    struct zsv_table *t = zsv_find((void *){c.params[0][1]});\n")
    w(f"    __atomic_fetch_add(&zsv_count[{index[n]}], 1, __ATOMIC_RELAXED);")
    w(f"    {'return ' if c.ret != 'void' else ''}((PFN_{n})t->fn[{index[n]}])({call});")
    w("}")
    if guard:
        w("#endif")
    w("")

w("static PFN_vkVoidFunction zsv_wrapper(int i)\n{\n    switch (i) {")
for n in names:
    if n in SPECIAL:
        continue
    guard = reg.guard(n)
    if guard:
        w(f"#ifdef {guard}")
    w(f"    case {index[n]}: return (PFN_vkVoidFunction)zsv_{n[2:]};")
    if guard:
        w("#endif")
w("    default: return NULL;\n    }\n}")

I = index
w(r"""
static int zsv_index(const char *name)
{
    for (int i = 0; i < ZSV_NCMD; i++)
        if (!strcmp(zsv_names[i], name))
            return i;
    return -1;
}

static VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zsv_GetInstanceProcAddr(VkInstance instance, const char *name);
static VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zsv_GetDeviceProcAddr(VkDevice device, const char *name);

static VKAPI_ATTR VkResult VKAPI_CALL zsv_CreateInstance(const VkInstanceCreateInfo *ci, const VkAllocationCallbacks *alloc,
                                                         VkInstance *instance)
{
    VkLayerInstanceCreateInfo *link = (VkLayerInstanceCreateInfo *)ci->pNext;
    PFN_vkGetInstanceProcAddr next;
    struct zsv_table *t;
    VkResult r;

    while (link && !(link->sType == VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO && link->function == VK_LAYER_LINK_INFO))
        link = (VkLayerInstanceCreateInfo *)link->pNext;
    if (!link)
        return VK_ERROR_INITIALIZATION_FAILED;
    next = link->u.pLayerInfo->pfnNextGetInstanceProcAddr;
    link->u.pLayerInfo = link->u.pLayerInfo->pNext;
    r = ((PFN_vkCreateInstance)next(VK_NULL_HANDLE, "vkCreateInstance"))(ci, alloc, instance);
    if (r != VK_SUCCESS)
        return r;

    zsv_start();
    __atomic_fetch_add(&zsv_count[%(ci)d], 1, __ATOMIC_RELAXED);
    if (ci->pApplicationInfo)
        zsv_note("instance\tapi\t%%u.%%u\napplication\t%%s\t%%s\n", VK_API_VERSION_MAJOR(ci->pApplicationInfo->apiVersion),
                 VK_API_VERSION_MINOR(ci->pApplicationInfo->apiVersion),
                 ci->pApplicationInfo->pApplicationName ? ci->pApplicationInfo->pApplicationName : "",
                 ci->pApplicationInfo->pEngineName ? ci->pApplicationInfo->pEngineName : "");
    for (uint32_t i = 0; i < ci->enabledExtensionCount; i++)
        zsv_note("extension\tinstance\t%%s\n", ci->ppEnabledExtensionNames[i]);
    zsv_chain("instance", ci->pNext);

    t = calloc(1, sizeof(*t));
    t->key = *(void **)*instance;
    t->handle = *instance;
    t->gipa = next;
    for (int i = 0; i < ZSV_NCMD; i++)
        if (zsv_level[i] == 'i')
            t->fn[i] = next(*instance, zsv_names[i]);
    zsv_add(t);
    return r;
}

static VKAPI_ATTR void VKAPI_CALL zsv_DestroyInstance(VkInstance instance, const VkAllocationCallbacks *alloc)
{
    struct zsv_table *t = instance ? zsv_find(instance) : NULL;

    if (!t)
        return;
    __atomic_fetch_add(&zsv_count[%(di)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkDestroyInstance)t->fn[%(di)d])(instance, alloc);
    zsv_remove(t);
    zsv_write();
}

static VKAPI_ATTR VkResult VKAPI_CALL zsv_CreateDevice(VkPhysicalDevice phys, const VkDeviceCreateInfo *ci,
                                                       const VkAllocationCallbacks *alloc, VkDevice *device)
{
    VkLayerDeviceCreateInfo *link = (VkLayerDeviceCreateInfo *)ci->pNext;
    struct zsv_table *it = zsv_find(phys), *t;
    PFN_vkGetInstanceProcAddr gipa;
    PFN_vkGetDeviceProcAddr gdpa;
    VkPhysicalDeviceProperties props;
    VkResult r;

    while (link && !(link->sType == VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO && link->function == VK_LAYER_LINK_INFO))
        link = (VkLayerDeviceCreateInfo *)link->pNext;
    if (!link || !it)
        return VK_ERROR_INITIALIZATION_FAILED;
    gipa = link->u.pLayerInfo->pfnNextGetInstanceProcAddr;
    gdpa = link->u.pLayerInfo->pfnNextGetDeviceProcAddr;
    link->u.pLayerInfo = link->u.pLayerInfo->pNext;
    r = ((PFN_vkCreateDevice)gipa(it->handle, "vkCreateDevice"))(phys, ci, alloc, device);
    ((PFN_vkGetPhysicalDeviceProperties)it->fn[%(gp)d])(phys, &props);
    if (r != VK_SUCCESS) {
        /* A refusal is the most interesting thing a survey can see: say what was asked for. */
        zsv_note("refused\tdevice\t%%s refused vkCreateDevice with VkResult %%d\n", props.deviceName, (int)r);
        for (uint32_t i = 0; i < ci->enabledExtensionCount; i++)
            zsv_note("extension\trefused-device\t%%s\n", ci->ppEnabledExtensionNames[i]);
        zsv_base("refused-device", ci->pEnabledFeatures);
        zsv_chain("refused-device", ci->pNext);
        return r;
    }

    __atomic_fetch_add(&zsv_count[%(cd)d], 1, __ATOMIC_RELAXED);
    zsv_note("device\tgpu\t%%s\ndevice\tdriver-api\t%%u.%%u\n", props.deviceName, VK_API_VERSION_MAJOR(props.apiVersion),
             VK_API_VERSION_MINOR(props.apiVersion));
    for (uint32_t i = 0; i < ci->enabledExtensionCount; i++)
        zsv_note("extension\tdevice\t%%s\n", ci->ppEnabledExtensionNames[i]);
    zsv_base("device", ci->pEnabledFeatures);
    zsv_chain("device", ci->pNext);

    t = calloc(1, sizeof(*t));
    t->key = *(void **)*device;
    t->handle = *device;
    t->gdpa = gdpa;
    for (int i = 0; i < ZSV_NCMD; i++)
        if (zsv_level[i] == 'd')
            t->fn[i] = gdpa(*device, zsv_names[i]);
    zsv_add(t);
    return r;
}

static VKAPI_ATTR void VKAPI_CALL zsv_DestroyDevice(VkDevice device, const VkAllocationCallbacks *alloc)
{
    struct zsv_table *t = device ? zsv_find(device) : NULL;

    if (!t)
        return;
    __atomic_fetch_add(&zsv_count[%(dd)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkDestroyDevice)t->fn[%(dd)d])(device, alloc);
    zsv_remove(t);
}

/*
 * ZSS_SURVEY_PRETEND=VK_a,VK_b adds those names to what a device says it
 * supports. It is for finding out which missing extension makes an
 * application turn a device down: the application gets as far as asking for
 * it, and the driver's refusal is then recorded. Nothing can work that way.
 */
static VKAPI_ATTR VkResult VKAPI_CALL zsv_EnumerateDeviceExtensionProperties(VkPhysicalDevice phys, const char *layer,
                                                                             uint32_t *count, VkExtensionProperties *props)
{
    struct zsv_table *t = zsv_find(phys);
    const char *pretend = getenv("ZSS_SURVEY_PRETEND");
    uint32_t real = 0, extra = 0, given;
    char list[1024], *save = NULL;
    VkResult r;

    __atomic_fetch_add(&zsv_count[%(ed)d], 1, __ATOMIC_RELAXED);
    if (!pretend || !pretend[0] || layer)
        return ((PFN_vkEnumerateDeviceExtensionProperties)t->fn[%(ed)d])(phys, layer, count, props);
    snprintf(list, sizeof(list), "%%s", pretend);
    for (char *tok = strtok_r(list, ",", &save); tok; tok = strtok_r(NULL, ",", &save))
        extra++;
    r = ((PFN_vkEnumerateDeviceExtensionProperties)t->fn[%(ed)d])(phys, NULL, &real, NULL);
    if (r != VK_SUCCESS)
        return r;
    if (!props) {
        *count = real + extra;
        return VK_SUCCESS;
    }
    given = *count < real ? *count : real;
    r = ((PFN_vkEnumerateDeviceExtensionProperties)t->fn[%(ed)d])(phys, NULL, &given, props);
    snprintf(list, sizeof(list), "%%s", pretend);
    for (char *tok = strtok_r(list, ",", &save); tok && given < *count; tok = strtok_r(NULL, ",", &save)) {
        memset(&props[given], 0, sizeof(props[given]));
        snprintf(props[given].extensionName, VK_MAX_EXTENSION_NAME_SIZE, "%%s", tok);
        props[given++].specVersion = 1;
    }
    *count = given;
    return given < real + extra ? VK_INCOMPLETE : VK_SUCCESS;
}

/* ZSS_SURVEY_PRETEND_TYPE=cpu|discrete|integrated reports the device as being of that type, for the same purpose. */
static void zsv_pretend_type(VkPhysicalDeviceProperties *p)
{
    const char *t = getenv("ZSS_SURVEY_PRETEND_TYPE");

    if (!t || !t[0])
        return;
    p->deviceType = !strcmp(t, "cpu") ? VK_PHYSICAL_DEVICE_TYPE_CPU
                  : !strcmp(t, "integrated") ? VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU : VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU;
}

static VKAPI_ATTR void VKAPI_CALL zsv_GetPhysicalDeviceProperties(VkPhysicalDevice phys, VkPhysicalDeviceProperties *out)
{
    struct zsv_table *t = zsv_find(phys);

    __atomic_fetch_add(&zsv_count[%(p1)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkGetPhysicalDeviceProperties)t->fn[%(p1)d])(phys, out);
    zsv_pretend_type(out);
}

static VKAPI_ATTR void VKAPI_CALL zsv_GetPhysicalDeviceProperties2(VkPhysicalDevice phys, VkPhysicalDeviceProperties2 *out)
{
    struct zsv_table *t = zsv_find(phys);

    __atomic_fetch_add(&zsv_count[%(p2)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkGetPhysicalDeviceProperties2)t->fn[%(p2)d])(phys, out);
    zsv_pretend_type(&out->properties);
}

static VKAPI_ATTR void VKAPI_CALL zsv_GetPhysicalDeviceProperties2KHR(VkPhysicalDevice phys, VkPhysicalDeviceProperties2 *out)
{
    struct zsv_table *t = zsv_find(phys);

    __atomic_fetch_add(&zsv_count[%(p2k)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkGetPhysicalDeviceProperties2KHR)t->fn[%(p2k)d])(phys, out);
    zsv_pretend_type(&out->properties);
}

/* ZSS_SURVEY_PRETEND_FEATURE=Struct.member,... reports those feature switches as on, for the same purpose. */
static void zsv_pretend_features(VkPhysicalDeviceFeatures2 *out)
{
    const char *pretend = getenv("ZSS_SURVEY_PRETEND_FEATURE");
    char want[160];
    int all;

    if (!pretend || !pretend[0])
        return;
    all = !strcmp(pretend, "ALL");
    for (VkBaseOutStructure *s = (VkBaseOutStructure *)out->pNext; s; s = s->pNext) {
        for (size_t i = 0; i < sizeof(zsv_feats) / sizeof(zsv_feats[0]); i++) {
            VkBool32 *b = (VkBool32 *)(s + 1);

            if (zsv_feats[i].stype != (int)s->sType)
                continue;
            for (int k = 0; k < zsv_feats[i].n; k++) {
                snprintf(want, sizeof(want), "%%s.%%s", zsv_feats[i].name, zsv_feats[i].members[k]);
                if (all || strstr(pretend, want)) {
                    if (!b[k])
                        zsv_note("pretended\tfeature\t%%s\n", want);
                    b[k] = VK_TRUE;
                }
            }
        }
    }
    for (size_t i = 0; i < sizeof(zsv_base_features) / sizeof(zsv_base_features[0]); i++) {
        snprintf(want, sizeof(want), "VkPhysicalDeviceFeatures.%%s", zsv_base_features[i]);
        if (all || strstr(pretend, want))
            ((VkBool32 *)&out->features)[i] = VK_TRUE;
    }
}

static VKAPI_ATTR void VKAPI_CALL zsv_GetPhysicalDeviceFeatures2(VkPhysicalDevice phys, VkPhysicalDeviceFeatures2 *out)
{
    struct zsv_table *t = zsv_find(phys);

    __atomic_fetch_add(&zsv_count[%(f2)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkGetPhysicalDeviceFeatures2)t->fn[%(f2)d])(phys, out);
    zsv_pretend_features(out);
}

static VKAPI_ATTR void VKAPI_CALL zsv_GetPhysicalDeviceFeatures2KHR(VkPhysicalDevice phys, VkPhysicalDeviceFeatures2 *out)
{
    struct zsv_table *t = zsv_find(phys);

    __atomic_fetch_add(&zsv_count[%(f2k)d], 1, __ATOMIC_RELAXED);
    ((PFN_vkGetPhysicalDeviceFeatures2KHR)t->fn[%(f2k)d])(phys, out);
    zsv_pretend_features(out);
}

static PFN_vkVoidFunction zsv_special(const char *name)
{
    if (!strcmp(name, "vkGetPhysicalDeviceProperties")) return (PFN_vkVoidFunction)zsv_GetPhysicalDeviceProperties;
    if (!strcmp(name, "vkGetPhysicalDeviceProperties2")) return (PFN_vkVoidFunction)zsv_GetPhysicalDeviceProperties2;
    if (!strcmp(name, "vkGetPhysicalDeviceProperties2KHR")) return (PFN_vkVoidFunction)zsv_GetPhysicalDeviceProperties2KHR;
    if (!strcmp(name, "vkGetPhysicalDeviceFeatures2")) return (PFN_vkVoidFunction)zsv_GetPhysicalDeviceFeatures2;
    if (!strcmp(name, "vkGetPhysicalDeviceFeatures2KHR")) return (PFN_vkVoidFunction)zsv_GetPhysicalDeviceFeatures2KHR;
    if (!strcmp(name, "vkEnumerateDeviceExtensionProperties")) return (PFN_vkVoidFunction)zsv_EnumerateDeviceExtensionProperties;
    if (!strcmp(name, "vkGetInstanceProcAddr")) return (PFN_vkVoidFunction)zsv_GetInstanceProcAddr;
    if (!strcmp(name, "vkGetDeviceProcAddr")) return (PFN_vkVoidFunction)zsv_GetDeviceProcAddr;
    if (!strcmp(name, "vkCreateInstance")) return (PFN_vkVoidFunction)zsv_CreateInstance;
    if (!strcmp(name, "vkDestroyInstance")) return (PFN_vkVoidFunction)zsv_DestroyInstance;
    if (!strcmp(name, "vkCreateDevice")) return (PFN_vkVoidFunction)zsv_CreateDevice;
    if (!strcmp(name, "vkDestroyDevice")) return (PFN_vkVoidFunction)zsv_DestroyDevice;
    return NULL;
}

/* A wrapper is handed out only for what the next in line really has, or the application would think it exists. */
static VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zsv_GetInstanceProcAddr(VkInstance instance, const char *name)
{
    PFN_vkVoidFunction special = zsv_special(name);
    struct zsv_table *t;
    int i;

    if (special)
        return special;
    if (!instance || !(t = zsv_find(instance)))
        return NULL;
    i = zsv_index(name);
    if (i < 0 || !zsv_wrapper(i))
        return t->gipa(instance, name);
    if (zsv_level[i] == 'i')
        return t->fn[i] ? zsv_wrapper(i) : NULL;
    return t->gipa(instance, name) ? zsv_wrapper(i) : NULL;
}

static VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zsv_GetDeviceProcAddr(VkDevice device, const char *name)
{
    struct zsv_table *t = device ? zsv_find(device) : NULL;
    int i;

    if (!t)
        return NULL;
    if (!strcmp(name, "vkGetDeviceProcAddr")) return (PFN_vkVoidFunction)zsv_GetDeviceProcAddr;
    if (!strcmp(name, "vkDestroyDevice")) return (PFN_vkVoidFunction)zsv_DestroyDevice;
    i = zsv_index(name);
    if (i < 0 || zsv_level[i] != 'd' || !zsv_wrapper(i))
        return t->gdpa(device, name);
    return t->fn[i] ? zsv_wrapper(i) : NULL;
}

VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zss_survey_GetInstanceProcAddr(VkInstance instance, const char *name)
{
    return zsv_GetInstanceProcAddr(instance, name);
}

VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL zss_survey_GetDeviceProcAddr(VkDevice device, const char *name)
{
    return zsv_GetDeviceProcAddr(device, name);
}
""" % {"p1": I["vkGetPhysicalDeviceProperties"], "p2": I["vkGetPhysicalDeviceProperties2"],
       "p2k": I["vkGetPhysicalDeviceProperties2KHR"], "f2": I["vkGetPhysicalDeviceFeatures2"], "f2k": I["vkGetPhysicalDeviceFeatures2KHR"],
       "ed": I["vkEnumerateDeviceExtensionProperties"], "ci": I["vkCreateInstance"], "di": I["vkDestroyInstance"], "cd": I["vkCreateDevice"], "dd": I["vkDestroyDevice"],
       "gp": I["vkGetPhysicalDeviceProperties"]})

open(out_path, "w").write("\n".join(o) + "\n")
