PACKAGE_NAME="zss"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="zss"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
